### ISSUE TITLE
Where is .env file ?

### ISSUE THREAD

**Issue by biswajitguha01** [Spencer-0003/Ashlyn#3]
I can’t find any prossess.env file

**Comment by Spencer-0003** [comment]
.env is purposely not in the repo as it contains details like the bot token etc but I could add an example .env file to the repo.

**Comment by Spencer-0003** [comment]
F

**Comment by biswajitguha01** [comment]
Thanks for your reply! I want to know know one thing what should write in mongo_db= ???

**Comment by Spencer-0003** [comment]
That would be the link to your mongo database, if you don't have one a guide to get one can be found here https://www.youtube.com/watch?v=rPqRyYJmx2g
